# params.yaml
project:
  name: Crypto Price Anomaly MVP
  version: 0.1.0

assets:
  - symbol: BTC/USDT
    exchange: binance
    type: spot
  - symbol: ETH/USDT
    exchange: binance
    type: spot

quote_override: null  # e.g. set to GBP to switch symbols programmatically

# Data frequency config
bar_interval: "30m"
start_date: "2025-06-01"
end_date: null  # change to 1m, 5m, 1h etc

# Feature parameters
return_col: log_return
zscore:
  lookback_bars: 96
  threshold: 2.5  # about 2 days at 30m

# Strategy parameters
mode: follow       # 'follow' or 'fade'
side: long_only    # allow_short later
hold_bars: 12        # 12 * 30m = 6h
max_positions: 1     # flat before new entry

# Costs
fees:
  taker_bps: 0.0005  # 5 bps per side
  slippage_bps: 0    # set >0 if you want friction

# Machine-learning model
model:
  use_ml: true            # overridden by --use-ML flag
  type: xgboost           # placeholder for future model swaps
  decision_threshold: 0.5 # probability threshold for long entries
  features:
    - zscore
    - log_return
    - log_return_mean_96
    - log_return_std_96
  params:                # passed to xgboost.XGBClassifier
    n_estimators: 20
    max_depth: 3
    learning_rate: 0.1
    subsample: 0.7
    colsample_bytree: 0.7

# Paths
paths:
  data_raw: data_raw
  data_proc: data_proc
  outputs: outputs
  logs: logs