# params_gbp.yaml  – quote currency switched to GBP (£)

project:
  name: Crypto Price Anomaly MVP (GBP)
  version: 0.1.0

assets:                     # pairs that trade natively in GBP on Kraken
  - symbol: BTC/GBP         # ccxt expects BTC for Kraken
    exchange: kraken
    type: spot
  - symbol: ETH/GBP
    exchange: kraken
    type: spot

quote_override: GBP         # downstream code can switch symbols programmatically

# Data frequency config
bar_interval: "30m"
start_date: "2025-01-01"
end_date: null

# Feature parameters
return_col: log_return
zscore:
  lookback_bars: 96
  threshold: 2.5

# Strategy parameters
mode: follow
side: long_only
hold_bars: 12
max_positions: 1

# Costs (Binance UK spot fees are usually 10 bps maker / 10 bps taker – adapt!)
fees:
  taker_bps: 0.001           # 10 bps per side
  slippage_bps: 0

# Machine-learning model
model:
  use_ml: true
  type: xgboost
  decision_threshold: 0.5
  features:
    - zscore
    - log_return
    - log_return_mean_96
    - log_return_std_96
  params:
    n_estimators: 20
    max_depth: 3
    learning_rate: 0.1
    subsample: 0.7
    colsample_bytree: 0.7

# Local paths
paths:
  data_raw:   data_raw
  data_proc:  data_proc
  outputs:    outputs
  logs:       logs